### ISSUE TITLE
issue converting proxied v8 java array to java object

### ISSUE THREAD

**Issue by narsinallamilli** [caoccao/Javet#351] opened 2024-06-06 12:23 UTC
Proxied Java V8 object is manipulated in javascript to set array field but it doesn't set. However List works.

`
public class Apple {
    private String[] appleColors;

    public String[] getAppleColors() {
        return appleColors;
    }

    public void setAppleColors(String[] appleColors) {
        this.appleColors = appleColors;
    }
}

//kotlin test
@Test
    fun testSamp() {
        try {
            val javetV8Engine = javetEngineV8Pool.getEngine()
            val javetV8Runtime = javetV8Engine.v8Runtime
            val javetBridgeConverter = JavetBridgeConverter()
            javetBridgeConverter.config.setReflectionObjectFactory(JavetReflectionObjectFactory.instance);
            javetV8Runtime.setConverter(javetBridgeConverter)
            val apple = Apple()
            javetV8Runtime.globalObject.set("apple", apple);
            javetV8Runtime.getExecutor("""
                        apple.appleColors = ['a']
                """.trimIndent()).executeVoid();
            println(apple.appleColors)
            javetV8Runtime.lowMemoryNotification()
        } catch (javetException: JavetException) {
            println(javetException)
        }
    }
`
Above test outputs
`
null
`
if the appleColors is changed to List<String> the output is 
`
[a]
`

**Comment by caoccao** [comment] 2024-06-07 04:30
This is the expected behavior: Native JS array is always converted to `List<Object>`.

**Comment by narsinallamilli** [comment] 2024-06-07 05:52
@caoccao the object classes are of third party libs, so there is not way I can change from Array to List, isn't there any workaround?
Do you mean List<Object> is set to Object[] type?

**Comment by caoccao** [comment] 2024-06-07 06:12
I think you may inject a JS function as follows.

1. Write a Java method (e.g. `list2Array`) that converts `List<Object>` to `Object[]`.
2. Inject that Java method as a JS function `list2Array`.
3. Call `external.acceptObjectArray(list2Array(nativeJSArray))`.

**Comment by caoccao** [comment] 2024-06-07 06:50
That might be possible, and indirect. I'll investigate that later. Please stay in tune.

**Comment by narsinallamilli** [comment] 2024-06-07 07:44
Thank you, I guess this should be handled by JavetProxyPluginArray.

**Comment by caoccao** [comment] 2024-06-07 08:30
I just added [V8ValueSealedArray](https://github.com/caoccao/Javet/commit/50d4787e6eaeb068577253cf0c463277bdf48bc4). Just call `Object.seal()` and you will get `Object[]` instead of `List<Object>`.

```java
assertArrayEquals(
        new Object[]{1, 2},
        v8Runtime.getExecutor("Object.seal([1,2])").executeObject());
assertArrayEquals(
        new Object[]{"a", "b"},
        v8Runtime.getExecutor("Object.seal(['a','b'])").executeObject());
assertArrayEquals(
        new Object[]{},
        v8Runtime.getExecutor("Object.seal([])").executeObject());
```

**Comment by caoccao** [comment] 2024-06-07 09:09
Please check this [commit](https://github.com/caoccao/Javet/commit/3844628a6a822897131416c4a765bfbef2ddf961) out. By calling `Object.seal()`, JS array will be converted to `Object[]` instead of `List<Object>`. This feature will be included in the next release. Please let me know if you have any questions. By the way, thank you for the donation!

```java
assertArrayEquals(
        new Object[]{1, 2},
        v8Runtime.getExecutor("Object.seal([1,2])").executeObject());
assertArrayEquals(
        new Object[]{"a", "b"},
        v8Runtime.getExecutor("Object.seal(['a','b'])").executeObject());
assertArrayEquals(
        new Object[]{},
        v8Runtime.getExecutor("Object.seal([])").executeObject());
```

**Closed** 2024-06-09 00:44 UTC
Labels: enhancement

**Comment by narsinallamilli** [comment] 2024-06-09 06:44
@caoccao 

I tested out this feature, however I see the the java array field is not set.

`
public class Apple {
    private String[] appleColors;


    public String[] getAppleColors() {
        return appleColors;
    }

    public void setAppleColors(String[] appleColors) {
        this.appleColors = appleColors;
    }
}

@Test
    fun testSamp() = try {
        val javetV8Engine = javetEngineV8Pool.getEngine()
        val javetV8Runtime = javetV8Engine.v8Runtime
        val javetBridgeConverter = JavetBridgeConverter()
        javetBridgeConverter.config.setReflectionObjectFactory(JavetReflectionObjectFactory.instance);
        javetBridgeConverter.config.setSealedEnabled(true)
        javetV8Runtime.converter = javetBridgeConverter
        val apple = Apple()
        javetV8Runtime.globalObject.set("apple", apple);
        javetV8Runtime.getExecutor("""
            apple.appleColors = Object.seal(['narsi'])
        """.trimIndent()).executeVoid()
        println(apple.appleColors)
        javetV8Runtime.lowMemoryNotification()

    } catch (javetException: JavetException) {
        println(javetException)

    }
`

output is
`
null
`

However if I change appleColors type to Object[] its works.

**Comment by caoccao** [comment] 2024-06-09 08:31
That is unfortunate. It's hard to cast `Object[]` to any other types of array, because:

1. The converter doesn't know the target type.
2. Even if the target type is known, the converter has to go over every element to validate the type. That's `O(N)` and impacts the performance considerably.

In this case, I suggest you implement your own proxy plugin. Please let me know if you have any questions.
