### ISSUE TITLE
Javet android high API level requeriments

### ISSUE THREAD

**Issue by jcrabanal** [caoccao/Javet#199] opened 2022-11-03 11:06 UTC
I have been checking several javet source files with the android linter, and there is plenty of classes that use methods not available on API levels that are on the range of the compatible levels according to the minSdk = 23 in build.gradle.

For example, com.caoccao.javet.interop.proxy.BaseJavetProxyHandler.addMethod(Method method, int startIndex, Map<String, List<Method>> map) makes use of Map.computeIfAbsent(), which is only available in API >= 24 (Android >= 7). There are plenty of other cases, many need API level 26 (Android >= 8).

I am worried about unexpected crashes if those methods are not properly guarded, or that needed compatibility code is not called.

I would like to have minSdk as low as possible. When running on an emulator with API level 21, I get this when loading the native lib:

E/dalvikvm( 3209): dlopen("/data/app-lib/com.xone.android.testv8_2-1/libjavet-v8-android.v.2.0.1.so") failed: dlopen failed: empty/missing DT_HASH in "libjavet-v8-android.v.2.0.1.so" (built with --hash-style=gnu?)

A quick google search tells me that the library shoud be compiled with -Wl,--hash-style=both to avoid this.

In Javenode, the native event loop class JNEventLoop seems to face similar issues.

**Comment by jcrabanal** [comment] 2022-11-03 11:40
Another example of usage of methods only present in high API levels:

In V8ValueObject.getBindingContext(), Method.getParameterCount() is used, however you can use int nParamCount = method.getParameterTypes().length; to do the same thing and works everywhere.

**Comment by caoccao** [comment] 2022-11-04 00:41
Thank @jcrabanal for raising these issues.

> I have been checking several javet source files with the android linter, and there is plenty of classes that use methods not available on API levels that are on the range of the compatible levels according to the minSdk = 23 in build.gradle.

Those API are taken care of by `coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:*.*.*")`. Projects referencing Javet Android inherit this dependency so that the API level incompatibility is not an issue. If you met such a problem, could you leave your sample project for me to check out?

> API level 21

Javet v1.0.7 is the last one supporting ABI 21. All the problems you described don't exist in that release. Of course, it was released long time ago, so please don't expect it to have some new features or bug fixes.

**Comment by jcrabanal** [comment] 2022-11-04 08:56
Aha, I've totally missed that because I've imported the source code files directly and messed with gradle files, sorry.

> Javet v1.0.7 is the last one supporting ABI 21. All the problems you described don't exist in that release. Of course, it was released long time ago, so please don't expect it to have some new features or bug fixes.

How hard would it be for me to add again support for lower API levels by compiling the native .so libraries? Is the dependency on higher API levels too high?

I need to support a lot of ancient devices.

**Comment by caoccao** [comment] 2022-11-04 09:36
As the doc denotes, new V8 no longer supports ABI < 23. The solution is to keep things rolling on branch v1.0.x. That also means to maintain 2 separate branches. I'm out of bandwidth doing so. If you are interested, you may keep working on that branch.

**Comment by caoccao** [comment] 2022-11-08 13:25
Please try the latest Javet with `JavetBridgeConverter` on a new Android device to see if this issue is resolved.

If the issue is gone, it will be how to port new features/fixes back to the v1.0.x branch.

**Comment by jcrabanal** [comment] 2022-11-10 16:22
That did the trick. Thanks for your help.

For me, I'll stick to Rhino in older Android versions. I have a wrapper ready so I can embed both engines.

**Comment by caoccao** [comment] 2022-11-11 00:24
That sounds good. And, so, the latest Javet does resolve the issue you met?

**Comment by jcrabanal** [comment] 2022-11-11 10:58
Not for this issue about varargs in particular (I had to apply the fix I mentioned earlier) but it's useful in other places.

**Comment by caoccao** [comment] 2022-11-11 12:27
I see. I think that is a bug to be fixed in the future.

**Closed** 2023-08-21 09:16 UTC
Labels: help wanted
