### ISSUE TITLE
Injecting a full Java instance into the V8 Context

### ISSUE THREAD

**Issue by newk5** [caoccao/Javet#12] opened 2021-04-02 04:17 UTC
So I am trying to expose Java functionality to the V8 context and for this and I would need to be able to inject instances of objects (not necessarily POJOS) into the V8 context. And while this is already possible, the process itself is a bit painful and hard to mantain ( unless I'm doing something wrong). I created a very small basic sample of what I mean. 

Let's imagine this is the class of the instance I want to inject:
```java

public class FileUtils {

    private String prefix;

    public FileUtils(String prefix) {
        this.prefix = prefix;
    }

    public void doA() {
        System.out.println(prefix+ "A");
    }

    public void doB() {
        System.out.println(prefix+"B");
    }

    public void add(Integer v1, Integer v2) {
        System.out.println(v1 + v2);
    }

}

```
Let's imagine this class belongs to an external library and has many many more methods with all sorts of diferent signatures. When I create a new instance of FileUtils, I would like to be able to inject that instance directly into the V8 context along with all those methods inside it, which, when called from javascript would trigger the java code inside them as shown above. So this is how I'm doing this at the moment:

I created a JavetObject converter and created a callback for every method inside the FileUtils class:
```java
@SuppressWarnings("unchecked")
public class EntityConverter extends JavetObjectConverter {

    @Override
    public V8Value toV8Value(V8Runtime v8, Object object) throws JavetException {
        V8Value v8Value = null;
        V8ValueObject v8ValueObject = null;

        v8Value = super.toV8Value(v8, object);
        if (v8Value != null && !(v8Value.isUndefined())) {
            return v8Value;
        }
        Class objectClass = object.getClass();
        v8ValueObject = v8.createV8ValueObject();
        for (Method method : objectClass.getMethods()) {
            String methodName = method.getName();

            try {
                FileUtilsCallbacks call = new FileUtilsCallbacks(v8, (FileUtils) object);
                JavetCallbackContext callback = new JavetCallbackContext(call, call.getMethod(methodName, method.getParameterTypes()));

                v8ValueObject.setFunction(methodName, callback);
            } catch (NoSuchMethodException ex) {
                Logger.getLogger(EntityConverter.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        v8Value = v8ValueObject;
        return v8.decorateV8Value(v8Value);

    }
}

```
And I created a JavetCallbackReceiver: 
```java
public class FileUtilsCallbacks extends JavetCallbackReceiver implements IJavetCallbackReceiver {

    private FileUtils myInstance;

    public FileUtilsCallbacks(V8Runtime v8Runtime, FileUtils myInstance) {
        super(v8Runtime);
        this.myInstance = myInstance;
    }

    //delegate the calls to the original instance 1 by 1
    public void doA() {
        this.myInstance.doA();
    }

    public void doB() {
        this.myInstance.doB();
    }

    public void add(Integer v1, Integer v2) {
        this.myInstance.add(v1, v2);
    }

}

```
And finally putting it all together:
```java
 public static void main(String[] args) throws JavetException {
        V8Runtime v8 = V8Host.getNodeInstance().createV8Runtime();

        FileUtils fileUtils = new FileUtils("Hello ");

       //create converter
        EntityConverter converter = new EntityConverter(); 
     

      //convert the fileUtils instance to a V8ValueObject
        V8ValueObject val = (V8ValueObject) converter.toV8Value(v8, fileUtils); 
        v8.getGlobalObject().set("fileUtils", val); //inject it into the V8 context
        
        //call the methods inside the fileUtils instance from javascript
        v8.getExecutor("fileUtils.doA(); fileUtils.doB(); fileUtils.add(1,1);").execute();

    }
```

All of the above is working perfectly without any issues. So what is the problem? Well, my issue here is with the JavetCallbackReceiver (FileUtilsCallbacks ), I had to duplicate every function inside the FileUtils class to put it inside the JavetCallbackReceiver (FileUtilsCallbacks ). For classes with many many methods, it's painful to have to duplicate each and every method. Is there a better way to achieve this without duplicating code and making sure it applies to all methods inside the classes?

**Comment by caoccao** [comment] 2021-04-02 06:01
Thank you for raising this. Actually, it's much simpler. Here are 3 tips. Please let me know if it works.

Direct Implementation
---

Just let `FileUtils` implement `IJavetCallbackReceiver` directly, then you don't need to duplicate it in another wrapper. In other words, `FileUtilsCallbacks` can be removed. `IJavetCallbackReceiver` in v0.8.0 is a little bit verbose. It is clean from v0.8.1.

``` java
public class FileUtils implements IJavetCallbackReceiver {
    // ...
}
```

Method is Method
---

Just add the method you get from class. There's no need to get it again. By the way, that's why I said _You don't need that `if-else`._

``` java
        for (Method method : objectClass.getMethods()) {
                JavetCallbackContext callbackContext = new JavetCallbackContext(receiver, method));
                v8ValueObject.setFunction(method.getName(), callbackContext);
        }
```

Converter is the Key
---

Exposing Java objects directly to V8 requires the converter to be able to handle all the objects that are not recognized by Javet built-in converter. As the tutorial presents, Javet leaves custom object conversion to derived converter for a few reasons. So, it's by design.

**Comment by newk5** [comment] 2021-04-02 14:32
> Thank you for raising this. Actually, it's much simpler. Here are 3 tips. Please let me know if it works.
> 
> ## Direct Implementation
> Just let `FileUtils` implement `IJavetCallbackReceiver` directly, then you don't need to duplicate it in another wrapper. In other words, `FileUtilsCallbacks` can be removed. `IJavetCallbackReceiver` in v0.8.0 is a little bit verbose. It is clean from v0.8.1.
> 
> ```java
> public class FileUtils implements IJavetCallbackReceiver {
>     // ...
> }
> ```
>

This is not viable for me because as I said above, the FileUtils class would be a class available in an external library so I dont have acess to it directly.


> ## Method is Method
> Just add the method you get from class. There's no need to get it again. By the way, that's why I said _You don't need that `if-else`._
> 
> ```java
>         for (Method method : objectClass.getMethods()) {
>                 JavetCallbackContext callbackContext = new JavetCallbackContext(receiver, method));
>                 v8ValueObject.setFunction(method.getName(), callbackContext);
>         }
> ```
> 
I tried this  and I changed my code above to this:

![image](https://user-images.githubusercontent.com/32560510/113424710-83dd6900-93c8-11eb-9284-3aa1550c8b6c.png)


but when calling the functions in javascript:
```java
v8.getExecutor("fileUtils.doA(); fileUtils.doB(); fileUtils.add(1,1);").execute();
```
 I get an exception:
```
Exception in thread "main" com.caoccao.javet.exceptions.JavetExecutionException: Error: object is not an instance of declaring class
	at com.caoccao.javet.interop.V8Native.execute(Native Method)
	at com.caoccao.javet.interop.NodeNative.execute(NodeNative.java:24)
	at com.caoccao.javet.interop.V8Runtime.execute(V8Runtime.java:287)
	at com.caoccao.javet.interop.executors.V8StringExecutor.execute(V8StringExecutor.java:56)
	at com.caoccao.javet.interop.IV8Executable.execute(IV8Executable.java:34)
	at NewMain1.main(NewMain1.java:33)

````

**Comment by caoccao** [comment] 2021-04-03 05:00
That is the typical exception on type conversation error. Here are my recommendations.

1. Please wait for v0.8.1 which allows **Object** and injecting custom converter to callback context.

2. Please implement a custom converter taking care of those unknown objects. The tutorials are good start.

v0.8.1 is coming...

**Comment by caoccao** [comment] 2021-04-04 04:14
`v0.8.1` is released. You no longer need to the implement anything. In other words, Javet is completed decoupled with the callback receiver.

Please checkout the [tutorial](https://github.com/caoccao/Javet/blob/main/docs/tutorial/manipulate_v8_function.rst) for detail.

**Comment by newk5** [comment] 2021-04-04 05:04
> `v0.8.1` is released. You no longer need to the implement anything. In other words, Javet is completed decoupled with the callback receiver.
> 
> Please checkout the [tutorial](https://github.com/caoccao/Javet/blob/main/docs/tutorial/manipulate_v8_function.rst) for detail.

I tried it and  I changed my entity converter to:
```java
public class EntityConverter extends JavetObjectConverter {

    @Override
    public V8Value toV8Value(V8Runtime v8, Object object) throws JavetException {
        V8Value v8Value = null;
        V8ValueObject v8ValueObject = null;

        v8Value = super.toV8Value(v8, object);
        if (v8Value != null && !(v8Value.isUndefined())) {
            return v8Value;
        }
        Class objectClass = object.getClass();
        v8ValueObject = v8.createV8ValueObject();
        for (Method method : objectClass.getMethods()) {
            JavetCallbackContext callback = new JavetCallbackContext(object, method);
            
            v8ValueObject.setFunction(method.getName(), callback);

        }

        v8Value = v8ValueObject;
        return v8.decorateV8Value(v8Value);

    }
}

```
And now it works, thanks!

I did notice something else though that I'm not really sure how to solve, for example, imagine the FileUtils class has a method to take in an int, for example "multiplyBy2"

```java
public class FileUtils {

    private String prefix;

    public FileUtils(String prefix) {
        this.prefix = prefix;
    }

    public void doA() {
        System.out.println(prefix+ "A");
    }

    public void doB() {
        System.out.println(prefix+"B");
    }

    public void add(Integer v1, Integer v2) {
        System.out.println(v1 + v2);
    }
    //new method
    public void multiplyBy2(int v){
        System.out.println(v*2);
    }

}
```
If I call that function from javascript like
```java
v8.getExecutor("fileUtils.multiplyBy2(2);").execute();
```
I get the error:
```
Exception in thread "main" com.caoccao.javet.exceptions.JavetExecutionException: Error: V8 callback signature mismatches: expected parameter type is int, actual parameter type is java.lang.Integer
	at com.caoccao.javet.interop.V8Native.execute(Native Method)
	at com.caoccao.javet.interop.NodeNative.execute(NodeNative.java:24)
```
I do understand if I change the method signature from int to Integer it will work, however in most cases I won't be able to do this because "FileUtils" would be a class from an external library. Is there a solution to this?

**Comment by caoccao** [comment] 2021-04-04 10:34
So far that's by design. There's a note at https://github.com/caoccao/Javet/blob/main/docs/tutorial/manipulate_v8_function.rst.

> Note: Primitive types must be in their object form in the method signature. E.g. boolean must be set to Boolean, int must be set to Integer, etc. Why? Because the converted value could be null which would cause JDK to complain with an exception.

I guess I was lazy while designing the core algorithm. Javet may handle this automatically, of course, the performance will be slightly impacted. I'll think it over.

**Comment by caoccao** [comment] 2021-04-06 04:51
Auto-type conversion for primitive types has been pushed to https://github.com/caoccao/Javet/commit/8f2a76211563b31ddc556c1a9700dd607a209824, and will be released in v0.8.2.

**Comment by caoccao** [comment] 2021-04-06 10:27
v0.8.2 is released. Enjoy.

**Comment by newk5** [comment] 2021-04-06 11:34
Thanks! I tested it and I can confirm its working.

**Closed** 2021-04-06 11:38 UTC
