### ISSUE TITLE
App crashes after calling V8Runtime.createV8ValueZonedDateTime() to convert java date objects

### ISSUE THREAD

**Issue by jcrabanal** [caoccao/Javet#217] opened 2022-12-09 16:33 UTC
I'm trying to convert java.util.Calendar and java.util.Date objects into javascript date objects.

I suppose the way to do this is like this:

`return (T) v8Runtime.createV8ValueZonedDateTime(((Calendar) object).getTimeInMillis());`

However javet crashes when I do that. It seems to be that the native library is calling the wrong JNI method. Android logcat shows this:

```
JNI DETECTED ERROR IN APPLICATION: the return type of CallObjectMethodV does not match long com.caoccao.javet.values.primitive.V8ValueZonedDateTime.toPrimitive()
                                                                                                    java_vm_ext.cc:594]     in call to CallObjectMethodV
                                                                                                    java_vm_ext.cc:594]     from java.lang.Object com.caoccao.javet.interop.V8Native.scriptRun(long, long, int, boolean)
```

I'd guess the problem is somewhere around line 673 in [javet_converter.cpp](https://github.com/caoccao/Javet/blob/main/cpp/jni/javet_converter.cpp). It looks like it is not using the same JNI method call like the other toPrimitive() methods.

**Comment by caoccao** [comment] 2022-12-09 23:46
Thank you for reporting this issue. Could you leave the minimal code snippet for me to reproduce this issue?

**Comment by jcrabanal** [comment] 2022-12-12 09:21
Here you have, just run it and the app will crash.

[TestJavetDate.zip](https://github.com/caoccao/Javet/files/10206463/TestJavetDate.zip)

**Comment by caoccao** [comment] 2022-12-13 02:59
I think you shouldn't subclass `JavetBridgeConverter`. `JavetProxyConverter` might be a better choice.

**Comment by jcrabanal** [comment] 2022-12-14 10:33
Tried that. Both bridge converter and proxy converter can turn Calendar and Date objects into proxied js values, but they are not real javascript Date objects. For this particular case, I need Date objects with its API and methods, that is why I went for createV8ValueZonedDateTime().

However, any V8ValueZonedDateTime that I create crashes the app when returning it from the java world.

**Comment by caoccao** [comment] 2022-12-15 01:17
- Use the proxy converter.
- Convert `Date` or `Calendar` to `ZonedDateTime` and let the proxy converter do the rest.
- Do not call `createV8ValueZonedDateTime()`.

**Comment by jcrabanal** [comment] 2022-12-15 11:34
Nope, same error, with vanilla javet. Here's the code I tried:

```
new Thread(() -> {
    String sResult;
    try {
        V8Runtime v8Runtime = V8Host.getV8Instance().createV8Runtime();
        JavetProxyConverter converter = new JavetProxyConverter();
        v8Runtime.setConverter(converter);
        V8Value jsJavaObject = converter.toV8Value(v8Runtime, new JavaObject());
        V8ValueGlobalObject globalObject = v8Runtime.getGlobalObject();
        globalObject.set("testJava", jsJavaObject);
        String sJs = readFile("test.js");
        IV8Executor executor = v8Runtime.getExecutor(sJs);
        V8Script script = executor.compileV8Script();
        V8Value result = script.execute();
        sResult = result.toString();
    } catch (Throwable t) {
        t.printStackTrace();
        sResult = t.getMessage();
    }
    String finalSResult = sResult;
    runOnUiThread(() -> {
        vText.setText(finalSResult);
    });
}).start();

```

test.js file:

```
function getNewDateFromJavaDate() {
    let jsDate = testJava.getDate();
    let sYear = jsDate.getFullYear();
    return sYear;
}

function getNewDateFromJavaCalendar() {
    let jsDate = testJava.getCalendar();
    let sYear = jsDate.getFullYear();
    return sYear;
}

function getNewDateFromZonedDateTime() {
    let jsDate = testJava.getZonedDateTime();
    let sYear = jsDate.getFullYear();
    return sYear;
}

function passDateObject() {
    testJava.passDateObject(new Date());
    return "1234";
}

getNewDateFromZonedDateTime();
//passDateObject();
```

JavaObject.java file:

```
import androidx.annotation.Keep;

import com.caoccao.javet.annotations.V8Allow;

import java.time.ZonedDateTime;
import java.util.Calendar;
import java.util.Date;

@Keep
public class JavaObject {

    @Keep
    @V8Allow
    public Date getDate() {
        return new Date();
    }

    @Keep
    @V8Allow
    public Calendar getCalendar() {
        return Calendar.getInstance();
    }

    @Keep
    @V8Allow
    public ZonedDateTime getZonedDateTime() {
        return ZonedDateTime.now();
    }

    @Keep
    @V8Allow
    public Object passDateObject(Object date) {
        if (date == null) {
            return "null value";
        }
        return date;
    }
}
```

I have noticed that it only crashes, when the java method returns ZonedDateTime (or V8ValueZonedDateTime in the previous tests). That is, if I modify public Object passDateObject(Object date) to return null or any other thing, it works, but I can't never return a ZonedDateTime back to the javascript world.

**Comment by caoccao** [comment] 2022-12-15 12:09
Thank you for the info. I'll check it out.

**Comment by caoccao** [comment] 2022-12-16 10:13
Good point. That might be the problem. I'll test it on Android later.

**Comment by caoccao** [comment] 2022-12-17 06:58
I guess I know what the problem is: `ZonedDateTime` is not available to ABI < 26. Please avoid using it in such legacy system and visit this [doc](https://developer.android.com/reference/java/time/ZonedDateTime) for more detail.

**Comment by jcrabanal** [comment] 2022-12-17 10:26
I've been running my tests on Android 9, 12 and 13.

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by caoccao** [comment] 2022-12-19 07:12
That bug was just fixed by this [commit](https://github.com/caoccao/Javet/commit/a19f16bddac7808f88665cebe797fea15901f29c). Thank you for your patience and please wait for the next release.

**Comment by jcrabanal** [comment] 2022-12-19 07:49
Awesome, thank you!

**Closed** 2023-10-27 14:53 UTC
Labels: bug
